name: Asp Net Core Deploy Pipeline Basic


on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest # Uses ubuntu os for environment
        
        steps:
            # Check code : Copy my repo for execution by github 
            - name:  Checkout code
              uses: actions/checkout@v4
            
            - name: Setup .Net
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: "10.0.x" # we use latest dotnet sdk 10 (lts)
            
            - name: Restore Dependencies
              run: dotnet restore
              
            - name: Build Project
              run: dotnet build --configuration Release --no-restore

