name: Asp Net Core Deploy Pipeline Basic


on:
    push:
        branches:
            - main

jobs: 
    deploy:
        runs-on : ubuntu-latest

        steps:
        - name: Deploy to Azure VPS
          uses: appleboy/ssh-action@v1.0.3     # used for ssh
          with:
            host: ${{secrets.VPS_HOST}}
            username: ${{secrets.VPS_USER}}
            key: ${{secrets.VPS_KEY}}
            script: |
             cd ~/deploy/Docker-Deploy-Learn
             git pull origin main
             docker-compose down 
             docker-compose up -d --build

